---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: raju
  become: false
  tasks:
    - name: Ensure 
      pip:
        name:
          - docker>=1.8.0
    - name: Pull Docker Image
      docker_image:
        name: "zhreya/calculators"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculators zhreya/calculators
